import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { NavLink, useNavigate } from "react-router-dom";
function NavLinks({ open }) {
    const navigate = useNavigate();
    return (_jsxs(_Fragment, { children: [_jsxs("div", { className: "hidden md:flex relative px-[4rem] md:w-full lg:w-full", children: [_jsx("div", { className: "absolute inset-0 bg-white/10  backdrop-blur-3xl pointer-events-none" }), _jsxs("ul", { className: "flex items-center text-white font-normal py-10 font-barlowCondensed h-full text-[1.6rem] gap-[4.8rem] justify-end w-full z-10 tracking-widest", children: [_jsx("li", { children: _jsx(NavLink, { className: ({ isActive }) => isActive ? "active-nav" : "hover-nav", to: "/", children: "HOME" }) }), _jsx("li", { children: _jsx(NavLink, { to: "/destination", className: ({ isActive }) => isActive ? "active-nav" : "hover-nav", children: "02 DESTINATION" }) }), _jsx("li", { children: _jsx(NavLink, { to: "/crew", className: ({ isActive }) => isActive ? "active-nav" : "hover-nav", children: "03 CREW" }) }), _jsx("li", { children: _jsx(NavLink, { to: "/technology", className: ({ isActive }) => isActive ? "active-nav" : "hover-nav", children: "04 TECHNOLOGY" }) })] })] }), _jsx("div", { className: `bg-white/5 backdrop-blur-xl md: md:hidden z-[90] flex h-screen w-[70%] right-0 top-0 absolute text-white pl-8 py-32 ${open ? "open" : "closed"}`, children: _jsxs("ul", { className: "flex flex-col items-start text-white font-normal py-10 font-barlowCondensed h-full text-[1.6rem] gap-4 justify-start w-full z-10 tracking-widest", children: [_jsxs("li", { onClick: () => {
                                navigate("/");
                            }, className: "flex group justify-between w-full items-center cursor-pointer", children: [_jsx("span", { children: "00 HOME" }), _jsx(NavLink, { to: "/", className: ({ isActive }) => isActive ? "active-nav-mobile" : "hover-nav-mobile" })] }), _jsxs("li", { onClick: () => {
                                navigate("/destination");
                            }, className: "flex group justify-between w-full items-center cursor-pointer", children: [_jsx("span", { children: "02 DESTINATION" }), _jsx(NavLink, { to: "/destination", className: ({ isActive }) => isActive ? "active-nav-mobile" : "hover-nav-mobile" })] }), _jsxs("li", { onClick: () => {
                                navigate("/crew");
                            }, className: "flex group justify-between w-full items-center cursor-pointer", children: [_jsx("span", { children: "03 CREW" }), _jsx(NavLink, { to: "/crew", className: ({ isActive }) => isActive ? "active-nav-mobile" : "hover-nav-mobile" })] }), _jsxs("li", { onClick: () => {
                                navigate("/technology");
                            }, className: "flex group justify-between w-full items-center cursor-pointer", children: [_jsx("span", { children: "04 TECHNOLOGY" }), _jsx(NavLink, { to: "/technology", className: ({ isActive }) => isActive ? "active-nav-mobile" : "hover-nav-mobile" })] })] }) })] }));
}
export default NavLinks;
